/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tkkjee (https://sketchfab.com/tkkjee)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/atom-cartoon-c744accbb4cc48dfbd0a8126d1a7f6d0
title: atom cartoon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Atom(props) {
  const { nodes, materials } = useGLTF('/atom.glb')
  const groupRef = useRef(null)

  useFrame(()=>{
    groupRef.current.rotation.x += 0.005;
  })

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[2,2,2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.6}>
            <group rotation={[2.53, 1.52, -Math.PI]}>
              <group position={[0, 0, 2.39]} rotation={[0.61, 0, 0]} scale={0.35}>
                <mesh geometry={nodes.Object_7.geometry} material={materials.blue} material-color="red" />
              </group>
            </group>
            <group rotation={[-1.7, 0.6, -2.11]}>
              <group position={[0, 0, -2.39]} rotation={[-0.61, 0, 2.09]} scale={0.35}>
                <mesh geometry={nodes.Object_10.geometry} material={materials.blue} />
              </group>
            </group>
            <group rotation={[-2.72, 0.47, 0.92]}>
              <group position={[-2.39, 0, 0]} rotation={[0.61, 0, -2.09]} scale={0.35}>
                <mesh geometry={nodes.Object_13.geometry} material={materials.blue} />
              </group>
            </group>
            <group rotation={[2.53, 1.52, -Math.PI]}>
              <mesh geometry={nodes.Object_15.geometry} material={materials.material_0} />
            </group>
            <group rotation={[-1.7, 0.6, -2.11]}>
              <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} />
            </group>
            <group rotation={[-2.72, 0.47, 0.92]}>
              <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
            </group>
            <mesh geometry={nodes.Object_4.geometry} material={materials.blue} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/atom.glb')
