/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LogoYounes(props) {
  const { nodes, materials } = useGLTF('/logoYounes.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Y.geometry} material={materials.Matériau} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Texte.geometry} material={materials.Material} position={[0.58, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Texte001.geometry} material={materials.Matériau} position={[2.68, 0.02, 0.01]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/logoYounes.glb')
