/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rtql8d (https://sketchfab.com/rtql8d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ps5-d788de3735964151a3e24fd59c0f1956
title: PS5
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Ps5(props) {
  const pathGlb = window.location.pathname === "localhost" ? "/ps5.glb" : "portfolio/ps5.glb";
  const { nodes, materials } = useGLTF(pathGlb);
  const ps5Ref = useRef(null);
  useFrame(() => {
    if(ps5Ref !== null) ps5Ref.current.rotation.y += 0.01;
  });
  return (
    <group {...props} dispose={null} ref={ps5Ref}>
      <group
        position={[0, -2.35, 0]}
        rotation={[-1.57, 0, 0]}
        scale={[2.5, 2.5, 2.5]}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["Glass_-_Heavy_Color"]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["Plastic_-_Textured_-_Regular"]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Plastic_-_Translucent_Glossy_Blue"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Plastic_-_Translucent_Glossy_Gray"]}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["Plastic_-_Translucent_Matte_Gray"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Plastic_-_Translucent_Matte_Gray_1"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Steel_-_Satin"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(pathGlb);
