/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SketchSupreme (https://sketchfab.com/sketchsupreme)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/the-omega-tier-100-skin-fortnite-3d-model-2d22241740ed4978814f0bf39c4615d8
title: The Omega Tier 100 Skin (Fortnite 3D Model)
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations, Html, OrbitControls } from "@react-three/drei";
import styled from "styled-components";
import AnimSphere from "./AnimSphere";
import { BiLoader } from "react-icons/bi";
import { flexCenter, primaryColor } from "../../Global.styles";



const Skin = (props) => {
  const pathGlb = window.location.pathname === "localhost" ? "/skin.glb" : "portfolio/skin.glb";
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(pathGlb);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Scene.play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.5, -3]} scale={[2, 2.5, 0.1]}>
        <mesh>
          <AnimSphere />
        </mesh>
      </group>
      <group name="Sketchfab_Scene" position={[0, 0, 0]}>
        <group
          name="Sketchfab_model"
          position={[0, -10, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.5, 0.5, 0.5]}
        >
          <group
            name="66b7841318dc433c91034e54ffb69da5fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="SK_M_MED_Carbide_Body_Armorao"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.08}
                  position={[0, 14, 0]}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_111"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />

                    <skinnedMesh
                      name="Object_112"
                      geometry={nodes.Object_112.geometry}
                      material={materials.M_Med_Carbide_Blue_Body}
                      skeleton={nodes.Object_112.skeleton}
                    />
                    <skinnedMesh
                      name="Object_113"
                      geometry={nodes.Object_113.geometry}
                      material={materials.M_Med_Carbide_Blue_Armor}
                      skeleton={nodes.Object_113.skeleton}
                    />
                    <skinnedMesh
                      name="Object_114"
                      geometry={nodes.Object_114.geometry}
                      material={materials.M_Med_Carbide_Black_Hat}
                      skeleton={nodes.Object_114.skeleton}
                    />
                    <skinnedMesh
                      name="Object_115"
                      geometry={nodes.Object_115.geometry}
                      material={materials.M_Med_Carbide_Black_Body}
                      skeleton={nodes.Object_115.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="SK_M_MED_Carbide_Body_Armormo"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload(pathGlb);

export default Skin;
